name: date_time_package
description: Package to put a popover widget to allow the user to set Date/Time
version: 0.0.3+0
author: Steven Smith

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mode_theme:
    git:
      url: https://github.com/GitHubStuff/mode_theme.git
  equatable: ^1.2.5
  flutter_bloc: ^6.1.0
  flutter_modular: ^1.3.2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
