name: picker_example
description: Example to show date/time picker
publish_to: "none"
version: 0.0.4+5

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Flutter SDK for internalization
    sdk: flutter
  # Add Project specific packages here ...
  date_time_package:
    path: ../
  font_awesome_flutter:
    git:
      url: https://github.com/GitHubStuff/font_awesome_flutter.git
  mode_theme:
    git:
      url: https://github.com/GitHubStuff/mode_theme.git
  # SQLite extras
  sqlite_controller:
    git:
      url: https://github.com/GitHubStuff/sqlite_controller.git
  sqlite_explorer:
    git:
      url: https://github.com/GitHubStuff/sqlite_explorer.git
  tracers:
    git:
      url: https://github.com/GitHubStuff/tracers.git
  after_layout: ^1.0.7+2 # Execute code after first layout
  auto_size_text: ^2.1.0 # Automatically resizes text to fit perfectly within its bounds.
  cupertino_icons: ^0.1.3
  enum_to_string: ^1.0.9
  equatable: ^1.2.0 # Needed for flutter_bloc
  flutter_bloc: ^6.0.1 # Widges to implement BLoC pattern
  flutter_modular: ^2.0.1 # Smart project structure with dependency injection and route management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: 'images/icon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - languages/en.json
